### PR TITLE
Update node_helper.js

### PR DESCRIPTION
**Pull request by thehigherlife**
updating to use the one call 3.0 api

### CODE REVIEW

**Comment by evilpulpo** [comment]
using this patch i still cannot get the app to output any data unfortunately. it just remains "loading" despite the API key working via URL (eg: https://api.openweathermap.org/data/3.0/onecall?lat=38.252666&lon=-85.758453&appid=*myapikey*)

**Comment by thehigherlife** [comment]
Are you getting anything from the Magic Mirror logs? I verified its still working for me with this patch.

**Comment by evilpulpo** [comment]
The out.log only displays:

[29.03.2023 16:02.36.378] [LOG]   [MMM-OpenWeatherMapForecast] 29-Mar-23 16:02 ** ERROR ** Latitude and/or longitude not provided.


however my module reads:

                {
                        module: "MMM-OpenWeatherMapForecast",
                        header: "Weather",
                        position: "bottom_left",
                        config: {
                                apikey: "myapikey",
                                latitutde: "38.252666",
                                longitude: "-85.758453",
                                iconset: "6oa",
                                forecastLayout: "table"
                        }
                },

**Comment by thehigherlife** [comment]
go pull my master branch again and see if that works.  I've verified that the version i'm using is identical to the version that is the master branch on my github page.  Are you using imperial or metric for your units?  Also are you running npm install in the directory after you clone it?  Are you running in docker?  If so, you have to run npm install inside the docker container for it to work.

**Comment by evilpulpo** [comment]
I'm using imperial as my units. I cloned the master branch repo (https://github.com/thehigherlife/MMM-OpenWeatherMapForecast), cd'd to the directory, ran npm install. I've changed nothing else, and MMM-OpenWeatherMapForecast replaces the spot where the original default weather module was (which also uses openweatherAPI, just not the 3.0 API, and does work). On the MM, it just displays "loading" but never loads. I'm not running in docker, just running it off raspi4b+ hardware

**Comment by thehigherlife** [comment]
in your config you have a typo:  latitutde instead of latitude

**Comment by evilpulpo** [comment]
i am an absolute idiot

**Comment by thehigherlife** [comment]
no worries.  glad we got it working!

**Comment by evilpulpo** [comment]
thank you for the help, wish original author would merge your work! you've brought the module back to life

**Comment by luxiouronimo** [comment]
is it just me or does the v3.0 api require a subscription with payment info, even if you limit it to the free 1k calls/day?

when i tried this update, it is stuck "Loading…", and the api returns the the following:

> {"cod":401, "message": "Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info."}

for this reason i don't think v3.0 should be the default, and i've added it as a config option named "endpoint".. have a look at this commit: https://github.com/MarcLandis/MMM-OpenWeatherMapForecast/commit/a0ead66f9e8f05b3d43f820dbb57aafdd8474ee3

**Comment by thehigherlife** [comment]
That works, you'll probably want to default to 3.0.  the problem is if you try to sign up today as a new user you can't get the 2.5 API access.  You can only get the 3.0 access so since I was new to OpenWeatherMap 3.0 was the only option.

**Comment by MarcLandis** [comment]
I have added the commit [@a0ead66](https://github.com/luxiouronimo/MMM-OpenWeatherMapForecast/commit/a0ead66f9e8f05b3d43f820dbb57aafdd8474ee3) by [luxiouronimo](https://github.com/luxiouronimo) 

Sorry for not merging this - I didn't notice the request.

**Pull request closed without merging**
